# SET DISTUTILS_USE_SDK=1
# conda env create --file environment.yml
# conda activate avis_gaussian_splatting

name: avis_gaussian_splatting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ninja
  - plyfile
  - tqdm
  - opencv
  - joblib
  - pip:
    - torch==2.1.0+cu121
    - torchvision==0.16.0+cu121
    - torchaudio==2.1.0+cu121
    - -f https://download.pytorch.org/whl/cu121/torch_stable.html
    - -e submodules/diff-gaussian-rasterization
    - -e submodules/simple-knn
    - -e submodules/fused-ssim
    - opencv-python