name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib


# name: gaussian_splatting
# channels:
#   - nvidia
#   - pytorch
#   - conda-forge
#   - defaults
# dependencies:
#   # Basis
#   - python=3.10
#   - pip
#   - ninja               # schnellerer C++-Build
#   - cmake               # für manche Submodule
  
#   # CUDA 11.8 Laufzeit und nvcc
#   - cudatoolkit=11.8
#   - cudatoolkit-dev=11.8
  
#   # PyTorch passend zu CUDA 11.8
#   - pytorch=2.1.0
#   - torchvision=0.16.0
#   - torchaudio=2.1.0
#   - pytorch-cuda=11.8    # sorgt dafür, dass PyTorch mit 11.8-Toolkit läuft

#   # Hilfs‑Pakete
#   - tqdm
#   - plyfile

#   # Pip‑Abhängigkeiten
#   - pip:
#       - opencv-python
#       - joblib
#       # Submodule bauen – nutzt jetzt CUDA 11.8 aus Conda
#       - submodules/diff-gaussian-rasterization
#       - submodules/simple-knn
#       - submodules/fused-ssim