Interface {
  Inputs {
    Field image {
      internalName = InImage.input0
    }
    Field mask {
      internalName = InMask.input0
    }
    Field scene {
      internalName = InScene.child
    }
  }
  Outputs {
  }
  Parameters {
    Field update {
      type = Trigger
    }
  }
}

Commands {
  source = $(LOCAL)/gaussian_splatting_export.py
}

Window {
  name = appWindow
  Button update {
    command = update
  }
}